### ISSUE TITLE
Spelling error in Activity

### ISSUE THREAD

**Issue by snebes** [SymfonyCasts/vue-challenges#6]
Found a spelling error when running through this tutorial on https://symfonycasts.com/screencast/vue/v-for/activity/367

In the question, this sentence is missing a "w":

> Now `e` want to loop through these fruits and show each of them in a span element.

**Comment by MolloKhan** [comment]
Hey @snebes thanks for reporting it

@shadowc could you take a look at it?

**Comment by shadowc** [comment]
I will!

**Comment by shadowc** [comment]
The typo has been fixed! Do we need to burst some cache @larzuk91 ?
